USE [master]
GO

/****** Object:  Database [Pescamas]    Script Date: 5/12/2023 7:07:31 p. m. ******/
CREATE DATABASE [Pescamas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pescamas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\Pescamas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pescamas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\Pescamas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pescamas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pescamas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pescamas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pescamas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pescamas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pescamas] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pescamas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pescamas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pescamas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pescamas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pescamas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pescamas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pescamas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pescamas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pescamas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pescamas] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Pescamas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pescamas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pescamas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pescamas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pescamas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pescamas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pescamas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pescamas] SET RECOVERY FULL 
GO

ALTER DATABASE [Pescamas] SET  MULTI_USER 
GO

ALTER DATABASE [Pescamas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pescamas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pescamas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pescamas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pescamas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pescamas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Pescamas] SET QUERY_STORE = ON
GO

ALTER DATABASE [Pescamas] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Pescamas] SET  READ_WRITE 
GO

